inherit_gem:
  action_policy: config/rubocop-rspec.yml
  jetrockets-standard: config/rails.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'
  NewCops: enable

Layout/ClassStructure:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Rails/DynamicFindBy:
  AllowedMethods: find_by_lowercase_email, find_by_slack_id, find_by_slack_id_or_email, find_by_valid_reset_password_token

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
